### ISSUE TITLE
Hl Groups

### ISSUE THREAD

**Issue by orhnk** [aPeoplesCalendar/apc.nvim#10]
The plugins lacks highlight groups which makes it harder to use it with multiple colorschemes

**Comment by snaeil** [comment]
Thanks for reporting @UTFeight 
Can you give an example (ideally including a screenshot)?
I didn't have any issues and were also using multiple colorschemes.

**Comment by orhnk** [comment]
Sorry...

Somehow I thought this plugin did not implement colorscheme specific attributes.

Here:

## Gruvbox Dark
![image](https://github.com/aPeoplesCalendar/apc.nvim/assets/101834410/e0466f6d-fac1-47e6-81ff-a7e641d7c7b9)

## Ayu Light
![image](https://github.com/aPeoplesCalendar/apc.nvim/assets/101834410/0ee6e679-6655-4dcc-a999-fedb22b60e95)

> [!NOTE]
> As you can see link highlights differ by the color scheme (which is how it should)

**Comment by snaeil** [comment]
@UTFeight you were right when you said highlight groups are not taken into account in the code.
So far this plugin's approach is to present the information as a specific filetype which will then be presented with filetype specific highlighting.
